import { defineField, defineType } from 'sanity'
import { DocumentTextIcon } from '@sanity/icons'

export const article = defineType({
  name: 'article',
  title: 'Article',
  type: 'document',
  icon: DocumentTextIcon,
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'metadata', title: 'Metadata' },
    { name: 'seo', title: 'SEO' },
    { name: 'relations', title: 'Relations' },
    { name: 'settings', title: 'Settings' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required().min(10).max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: { source: 'title', maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      group: 'content',
      rows: 4,
      description: 'Shown in listings and social previews (max 300 chars)',
      validation: (rule) => rule.required().max(300),
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'array',
      group: 'content',
      of: [
        { type: 'block', styles: [{ title: 'Normal', value: 'normal' }, { title: 'H2', value: 'h2' }, { title: 'H3', value: 'h3' }, { title: 'H4', value: 'h4' }, { title: 'Quote', value: 'blockquote' }], lists: [{ title: 'Bullet', value: 'bullet' }, { title: 'Numbered', value: 'number' }], marks: { decorators: [{ title: 'Strong', value: 'strong' }, { title: 'Emphasis', value: 'em' }, { title: 'Code', value: 'code' }, { title: 'Underline', value: 'underline' }, { title: 'Strikethrough', value: 'strike-through' }], annotations: [{ title: 'Link', name: 'link', type: 'object', fields: [{ name: 'href', type: 'url', title: 'URL' }, { name: 'blank', type: 'boolean', title: 'Open in new tab' }] }] } },
        { type: 'image', options: { hotspot: true }, fields: [{ name: 'alt', type: 'string', title: 'Alt Text', validation: (rule) => rule.required() }, { name: 'caption', type: 'string', title: 'Caption' }, { name: 'attribution', type: 'string', title: 'Attribution' }] },
        { type: 'figure' },
        { type: 'callout' },
        { type: 'code' },
        { type: 'table' },
        { type: 'blockquote' },
      ],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'featuredImage',
      title: 'Featured Image',
      type: 'image',
      group: 'content',
      options: { hotspot: true },
      fields: [
        { name: 'alt', type: 'string', title: 'Alt Text', validation: (rule) => rule.required() },
        { name: 'caption', type: 'string', title: 'Caption' },
        { name: 'attribution', type: 'string', title: 'Attribution' },
      ],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'healthTopic',
      title: 'Health Topic',
      type: 'reference',
      group: 'metadata',
      to: [{ type: 'healthTopic' }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'subTopics',
      title: 'Sub-Topics',
      type: 'array',
      group: 'metadata',
      of: [{ type: 'reference', to: [{ type: 'healthTopic' }] }],
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      group: 'metadata',
      of: [{ type: 'reference', to: [{ type: 'tag' }] }],
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'string',
      group: 'metadata',
      initialValue: 'Adeola James',
      readOnly: true,
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      group: 'metadata',
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'updatedAt',
      title: 'Updated At',
      type: 'datetime',
      group: 'metadata',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'settings',
      options: { list: ['draft', 'published', 'archived'], layout: 'radio' },
      initialValue: 'draft',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'series',
      title: 'Series',
      type: 'reference',
      group: 'relations',
      to: [{ type: 'series' }],
    }),
    defineField({
      name: 'relatedArticles',
      title: 'Related Articles',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'article' }] }],
      description: 'Manually curated (max 4)',
      validation: (rule) => rule.max(4),
    }),
    defineField({
      name: 'productRefs',
      title: 'Product References',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'product' }] }],
      description: 'Affiliate products mentioned',
    }),
    defineField({
      name: 'readingTime',
      title: 'Reading Time (minutes)',
      type: 'number',
      group: 'settings',
      description: 'Auto-calculated on publish, editable for override',
    }),
    defineField({
      name: 'tableOfContents',
      title: 'Table of Contents',
      type: 'array',
      group: 'settings',
      of: [{ type: 'tocItem' }],
      description: 'Auto-generated from headings',
    }),
    defineField({
      name: 'showMedicalDisclaimer',
      title: 'Show Medical Disclaimer',
      type: 'boolean',
      group: 'settings',
      initialValue: true,
    }),
    defineField({
      name: 'showAffiliateDisclosure',
      title: 'Show Affiliate Disclosure',
      type: 'boolean',
      group: 'settings',
      initialValue: false,
    }),
    defineField({
      name: 'canonicalUrl',
      title: 'Canonical URL',
      type: 'url',
      group: 'seo',
      description: 'If syndicated from another source',
    }),
    defineField({
      name: 'metaTitle',
      title: 'Meta Title',
      type: 'string',
      group: 'seo',
      validation: (rule) => rule.max(60),
      description: 'Defaults to article title',
    }),
    defineField({
      name: 'metaDescription',
      title: 'Meta Description',
      type: 'text',
      group: 'seo',
      rows: 3,
      validation: (rule) => rule.max(160),
      description: 'Defaults to excerpt',
    }),
    defineField({
      name: 'ogImage',
      title: 'Open Graph Image',
      type: 'image',
      group: 'seo',
      options: { hotspot: true },
      description: '1200x630px recommended',
    }),
    defineField({
      name: 'noIndex',
      title: 'No Index',
      type: 'boolean',
      group: 'seo',
      initialValue: false,
    }),
    defineField({
      name: 'noFollow',
      title: 'No Follow',
      type: 'boolean',
      group: 'seo',
      initialValue: false,
    }),
  ],
  preview: {
    select: { title: 'title', status: 'status', media: 'featuredImage', publishedAt: 'publishedAt' },
    prepare({ title, status, media, publishedAt }) {
      return { title, subtitle: `${status} • ${publishedAt ? new Date(publishedAt).toLocaleDateString() : 'Not published'}`, media }
    }
  },
  orderings: [
    { title: 'Published Date (New)', name: 'publishedAtDesc', by: [{ field: 'publishedAt', direction: 'desc' }] },
    { title: 'Published Date (Old)', name: 'publishedAtAsc', by: [{ field: 'publishedAt', direction: 'asc' }] },
    { title: 'Title A-Z', name: 'titleAsc', by: [{ field: 'title', direction: 'asc' }] },
  ],
})